name: Build webhook images
run-name: build-webhook-images
on:
  push:
    branches:
      - "main"
jobs:
  build-test-images:
    name: Build test images
    runs-on: ubuntu-latest

    steps:

      - id: set_build_image_tag
        name: Set build image tag
        run: echo "BUILDIMAGE=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUPUT

      - id: checkout_repo
        name: Checkout repo
        uses: actions/checkout@v3

      - id: ghcr_login
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: build_test_image_ubuntu
        name: Build Ubuntu test image
        uses: docker/build-push-action@v4.1.1
        with:
          context: ${{ github.workspace }}/Dockerfiles
          push: false
          file: Dockerfile.ubuntu
          tags: ${{ steps.set_build_image_tag.outputs.BUILDIMAGE }}